server:
  port: 1002


eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: localhost

spring:
  application:
    name: Service2