server:
  port: 1001


# eureka:
  # client:
    # service-url:
      # defaultZone: http://localhost:1000/eureka/
    
  instance:
    hostname: localhost

spring:
  application:
    name: Service1
    
family:
  people:
    6
  address:
    fujian三明